### ISSUE TITLE
Aplikacja się nie odpala

### ISSUE THREAD

**Issue by event15** [stasbar/tax-ledger-cli#2]
Na MacOS High Sierra 10.13.2
MacBook Pro (Retina)
2,3 GHz Intel Core i7

Aplikacja pokazuje się w applications, aczkolwiek próba uruchomienia od razu wyłącza ją. Nawet okienko się nie pokazuje

**Comment by stasbar** [comment]
Aplikacja na macOS tak naprawdę odpala polecenie w Terminalu, tak więc odpalasz aplikacje, a potem otwierasz okno Terminala z Docka (który powinien zostać uruchomiony). 
Fakt, nie najlepsze rozwiązanie, ale do czasu GUI niestety lepszego nie znam :D

**Comment by event15** [comment]
No ok, dobrze wiedzieć :D 
Swoją drogą był jakiś specjalny powód dla Kotlina, czy po prostu w tym piszesz i najszybciej Ci było?

**Comment by stasbar** [comment]
Wybrałem Kotlina, bo to tak naprawdę Java, tylko o wiele produktywniejsza i przyjemniejsza w pisaniu. Dodatkowo jest wieloplatformowa, a więc niewielki skok jeśli chciałbym zrobić klienta na Androida. 
Niestety jednak będę musiał przepisać cały kod na JavaScript/TS, bo Java nie nadaje się do tworzenia aplikacji z GUI. O wiele nowocześniejsze rozwiązania ma JS ze swoim ElectronJS.
Dodatkowo program szybciej widzę w przeglądarce, niż na Androida, chociaż Reference Implementation i tak będzie rozwijane w Kotlinie.
