### ISSUE TITLE
Wypłaty z bitbay nie wyświetlają się

### ISSUE THREAD

**Issue by kubasienki** [stasbar/tax-ledger-cli#6]
Nie wyświetlają się wypłaty **kryptowalutowe** niezależnie od użytej flagi przy poleceniu transactions.
Czy to pożądane zachowanie i np. tylko wypłaty złotówkowe powinny się wyświetlać?

**Comment by stasbar** [comment]
Tak, wypłaty kryptowalut się nie wyświetlają ponieważ nie mają żadnej informacji do celów podatkowych.  Istotnie są tylko operacje sprzedaży oraz kupna. To, że aplikacja pokazuję wpłaty i wypłaty w PLN jest bardziej jako ciekawostka niżeli istotna informacja, innymi słowy nikogo nie interesuje gdzie trzymasz swoje złotówki, czy na koncie bankowym, czy na koncie giełdowym, czy w sejfie czy gdziekolwiek. Ważne jest to co robisz z tymi złotówkami, czy zamieniasz je na/za inne wartości.
Temat jest bardzo obszerny, a dokładniej zostało wszystko opisane w najnowszej wersji aplikacji która jest aktualnie w wersji beta i można ją pobrać pod linkiem: https://tax-ledger.com/
